bug combat rows don't align Fixes #108
sun-dragon-cult/fvtt-system-rqg pull request #109
Opened 2021-12-22 02:31 UTC by Moonpile

div needed style="display: block"

2021-12-22 19:13 UTC, wake42 requested changes

2021-12-22 19:13 UTC, wake42 commented on src/actors/sheet-parts/gear-tab.hbs
> +            <div data-item-id="{{id}}" class="gear contextmenu" style="display: block;">
see if you can modify the rqg.scss instead of hardcoding the styling

2021-12-25 19:55 UTC, Moonpile commented
OH GOD this took me forever and gave me feelings of inadequacy!  I did however correct something beyond just the "usage" styles now being in css.  If the weapon only has one usage then the usage cells (Skill, Damage, STR, DEX) line up with the common non-usage cells (Name HP, Price, ENC, Location).  If the weapon has more than one usage cell then the non-usage cells "straddle" the usage cells to make it clear that they apply to the weapon overall and not just the usage, as shown below.

![image](https://user-images.githubusercontent.com/3959760/147392627-818a35bb-98b7-4304-8965-3fc0eac59c55.png)

2021-12-25 19:56 UTC, Moonpile commented
OH GOD this took me forever and gave me feelings of inadequacy!  I did however correct something beyond just the "usage" styles now being in css.  If the weapon only has one usage then the usage cells (Skill, Damage, STR, DEX) line up with the common non-usage cells (Name HP, Price, ENC, Location).  If the weapon has more than one usage cell then the non-usage cells "straddle" the usage cells to make it clear that they apply to the weapon overall and not just the usage, as shown below.

![image](https://user-images.githubusercontent.com/3959760/147392627-818a35bb-98b7-4304-8965-3fc0eac59c55.png)

2021-12-25 22:54 UTC, wake42 approved these changes

2021-12-25 23:53 UTC, merged