Moonpile/Human-Template-include-items-#481
sun-dragon-cult/fvtt-system-rqg pull request #486
Opened 2023-02-24 03:49 UTC by Moonpile

Fixes #481

- Used the Sartar text from the wiki in the Human (Sartarite)

2023-02-24 03:54 UTC, Moonpile commented
I created a vanilla "Human (Base)" and moved it to the bestiary.  This gets rid of the species-templates pack and breaks the Adventurer Wizard, but that is already well-broken.  I also created a "Human (Sartarite)" that has the cultural skills, rune, and passions pre-applied.  I didn't do the other homelands on the thinking that they will get included in the RQG module.

The "Customs ()" skills were using homelands.  I changed it to use cultures and agree with the skills as named in the "Homeland Cultural Skill Bonuses" from RQG p 60-63.  

Fixed the Kick skill name.

Removed the ui.notificication.errors in applyFnToItemFromHandlebarsArgs

2023-02-24 04:33 UTC, Moonpile commented
I accidentally fixed #482 on the same branch so I added it to this PR.

2023-02-26 01:02 UTC, wake42 requested changes
demo-actors & demo-items compendiums are still defined in system.json resulting in empty compendiums so they need to be removed.

2023-02-26 01:02 UTC, wake42 commented on src/i18n/en/openSystem.json
> +      "atlatl": {
Should be plural
```suggestion
      "atlatls": {
```

2023-02-26 19:01 UTC, Moonpile commented
> demo-actors & demo-items compendiums are still defined in system.json resulting in empty compendiums so they need to be removed.

If we have a pack defined in system.json and there's not a corresponding directory in pack-templates, should we be getting a warning during build?  If so I think that can be a chore issue for another version.

2023-02-26 19:11 UTC, Moonpile commented on src/i18n/en/openSystem.json
> +      "atlatl": {
Fixed

2023-02-26 22:44 UTC, wake42 approved these changes

2023-02-26 23:05 UTC, merged